// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxrqwudshvzgtcazfrhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4cnF3dWRzaHZ6Z3RjYXpmcmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNTMzMjYsImV4cCI6MjA1NDYyOTMyNn0.nUDOPvCubX_xK8fNf5VO8KAPRb5aqExSZd-xvaSo_2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);